# Generated by Django 4.0.4 on 2022-05-10 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('productName', models.CharField(max_length=100)),
                ('countStock', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('storeName', models.CharField(max_length=50)),
                ('salesProducts', models.ManyToManyField(to='stoktakip.product')),
            ],
        ),
    ]
