# Generated by Django 4.0.4 on 2022-05-10 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stoktakip', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Store',
        ),
    ]
