# Generated by Django 4.0.4 on 2022-05-10 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stoktakip', '0002_delete_store'),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('storeName', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='InStoreProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salesProducts', models.ManyToManyField(to='stoktakip.product')),
                ('storeName', models.ManyToManyField(to='stoktakip.store')),
            ],
        ),
    ]
