# Generated by Django 4.0.4 on 2022-05-10 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stoktakip', '0003_store_instoreproducts'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InStoreProducts',
        ),
    ]
