# Generated by Django 4.0.4 on 2022-05-10 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stoktakip', '0004_delete_instoreproducts'),
    ]

    operations = [
        migrations.CreateModel(
            name='InStoreProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storeStock', models.IntegerField()),
                ('salesProducts', models.ManyToManyField(to='stoktakip.product')),
                ('storeName', models.ManyToManyField(to='stoktakip.store')),
            ],
        ),
    ]
