# Generated by Django 4.0.4 on 2022-05-11 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stoktakip', '0005_instoreproducts'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InStoreProducts',
        ),
    ]
