# Generated by Django 4.0.4 on 2022-05-11 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stoktakip', '0006_delete_instoreproducts'),
    ]

    operations = [
        migrations.CreateModel(
            name='InStoreProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salesProductId', models.IntegerField(unique=True)),
                ('storeStock', models.IntegerField()),
                ('salesProducts', models.ManyToManyField(to='stoktakip.product')),
                ('storeName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stoktakip.store')),
            ],
        ),
    ]
